### ISSUE TITLE
Appending to an HDF5 does not work (can it?)

### ISSUE THREAD

**Issue by StephanPreibisch** [saalfeldlab/n5-hdf5#21]
Hi, I am trying to write to an existing HDF5 file, i.e. add new datasets in there. It does so without complaining and the file size increases, but the resulting file does not list the new datasets. Have you ever tried that, should that work @axtimwalde?

Thanks so much,
Stephan

**Comment by axtimwalde** [comment]
Close it?  E.g. with auto-close
```java
try (var writer = new N5HDF5Writer(...)) {
  ... write ...
}
```

**Comment by StephanPreibisch** [comment]
nice, that worked!
<img width="1425" alt="Screen Shot 2022-11-15 at 10 53 45 AM" src="https://user-images.githubusercontent.com/1420587/201965096-a3aeb021-4bb9-47c7-b306-7c78e7c53b79.png">

**Comment by StephanPreibisch** [comment]
thanks so much!

**Comment by axtimwalde** [comment]
Just to make sure that this works in all scenarios, all `N5Writer` and `N5Reader` should be closed after finishing their work.  For 'normal' filesystem or cloud writers including Zarr this is not necessary, but it doesn't hurt.  The handles are also closed automatically when the JVM goes down, but in an application like BigStitcher, this could take a while.

**Comment by StephanPreibisch** [comment]
It seems like specifically System.exit() calls might cause problems in this scenario, which we often use when running Spark ...

**Comment by StephanPreibisch** [comment]
Unfortunately I am still working with an older version of N5 (due to Spark) that does not have a close() call yet, only the specific N5HDF5Writer has ...
